//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class imageEntities {
    
    private string thumbnailImageField;
    
    private string mediumImageField;
    
    private string largeImageField;
    
    private string entityTypeField;
    
    private imageEntities[] imageEntities1Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string thumbnailImage {
        get {
            return this.thumbnailImageField;
        }
        set {
            this.thumbnailImageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string mediumImage {
        get {
            return this.mediumImageField;
        }
        set {
            this.mediumImageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string largeImage {
        get {
            return this.largeImageField;
        }
        set {
            this.largeImageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string entityType {
        get {
            return this.entityTypeField;
        }
        set {
            this.entityTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("imageEntities")]
    public imageEntities[] imageEntities1 {
        get {
            return this.imageEntities1Field;
        }
        set {
            this.imageEntities1Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class searchresponse {
    
    private string queryField;
    
    private string sortField;
    
    private string responseGroupField;
    
    private string totalResultsField;
    
    private string startField;
    
    private string numItemsField;
    
    private string facetsField;
    
    private searchresponseItemsItem[][] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string query {
        get {
            return this.queryField;
        }
        set {
            this.queryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sort {
        get {
            return this.sortField;
        }
        set {
            this.sortField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string responseGroup {
        get {
            return this.responseGroupField;
        }
        set {
            this.responseGroupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string totalResults {
        get {
            return this.totalResultsField;
        }
        set {
            this.totalResultsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string numItems {
        get {
            return this.numItemsField;
        }
        set {
            this.numItemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string facets {
        get {
            return this.facetsField;
        }
        set {
            this.facetsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", typeof(searchresponseItemsItem), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public searchresponseItemsItem[][] items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class searchresponseItemsItem {
    
    private string itemIdField;
    
    private string parentItemIdField;
    
    private string nameField;
    
    private string msrpField;
    
    private string salePriceField;
    
    private string upcField;
    
    private string categoryPathField;
    
    private string shortDescriptionField;
    
    private string longDescriptionField;
    
    private string thumbnailImageField;
    
    private string mediumImageField;
    
    private string largeImageField;
    
    private string productTrackingUrlField;
    
    private string standardShipRateField;
    
    private string marketplaceField;
    
    private string modelNumberField;
    
    private string sellerInfoField;
    
    private string productUrlField;
    
    private string customerRatingField;
    
    private string numReviewsField;
    
    private string customerRatingImageField;
    
    private string categoryNodeField;
    
    private string bundleField;
    
    private string stockField;
    
    private string addToCartUrlField;
    
    private string affiliateAddToCartUrlField;
    
    private string freeShippingOver50DollarsField;
    
    private string offerTypeField;
    
    private string isTwoDayShippingEligibleField;
    
    private string availableOnlineField;
    
    private searchresponseItemsItemGiftOptions[] giftOptionsField;
    
    private imageEntities[] imageEntitiesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string itemId {
        get {
            return this.itemIdField;
        }
        set {
            this.itemIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string parentItemId {
        get {
            return this.parentItemIdField;
        }
        set {
            this.parentItemIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string msrp {
        get {
            return this.msrpField;
        }
        set {
            this.msrpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string salePrice {
        get {
            return this.salePriceField;
        }
        set {
            this.salePriceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string upc {
        get {
            return this.upcField;
        }
        set {
            this.upcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string categoryPath {
        get {
            return this.categoryPathField;
        }
        set {
            this.categoryPathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string shortDescription {
        get {
            return this.shortDescriptionField;
        }
        set {
            this.shortDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string longDescription {
        get {
            return this.longDescriptionField;
        }
        set {
            this.longDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string thumbnailImage {
        get {
            return this.thumbnailImageField;
        }
        set {
            this.thumbnailImageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string mediumImage {
        get {
            return this.mediumImageField;
        }
        set {
            this.mediumImageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string largeImage {
        get {
            return this.largeImageField;
        }
        set {
            this.largeImageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string productTrackingUrl {
        get {
            return this.productTrackingUrlField;
        }
        set {
            this.productTrackingUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string standardShipRate {
        get {
            return this.standardShipRateField;
        }
        set {
            this.standardShipRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string marketplace {
        get {
            return this.marketplaceField;
        }
        set {
            this.marketplaceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string modelNumber {
        get {
            return this.modelNumberField;
        }
        set {
            this.modelNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sellerInfo {
        get {
            return this.sellerInfoField;
        }
        set {
            this.sellerInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string productUrl {
        get {
            return this.productUrlField;
        }
        set {
            this.productUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string customerRating {
        get {
            return this.customerRatingField;
        }
        set {
            this.customerRatingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string numReviews {
        get {
            return this.numReviewsField;
        }
        set {
            this.numReviewsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string customerRatingImage {
        get {
            return this.customerRatingImageField;
        }
        set {
            this.customerRatingImageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string categoryNode {
        get {
            return this.categoryNodeField;
        }
        set {
            this.categoryNodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string bundle {
        get {
            return this.bundleField;
        }
        set {
            this.bundleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string stock {
        get {
            return this.stockField;
        }
        set {
            this.stockField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string addToCartUrl {
        get {
            return this.addToCartUrlField;
        }
        set {
            this.addToCartUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string affiliateAddToCartUrl {
        get {
            return this.affiliateAddToCartUrlField;
        }
        set {
            this.affiliateAddToCartUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string freeShippingOver50Dollars {
        get {
            return this.freeShippingOver50DollarsField;
        }
        set {
            this.freeShippingOver50DollarsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string offerType {
        get {
            return this.offerTypeField;
        }
        set {
            this.offerTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string isTwoDayShippingEligible {
        get {
            return this.isTwoDayShippingEligibleField;
        }
        set {
            this.isTwoDayShippingEligibleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string availableOnline {
        get {
            return this.availableOnlineField;
        }
        set {
            this.availableOnlineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("giftOptions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public searchresponseItemsItemGiftOptions[] giftOptions {
        get {
            return this.giftOptionsField;
        }
        set {
            this.giftOptionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("imageEntities")]
    public imageEntities[] imageEntities {
        get {
            return this.imageEntitiesField;
        }
        set {
            this.imageEntitiesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class searchresponseItemsItemGiftOptions {
    
    private string allowGiftWrapField;
    
    private string allowGiftMessageField;
    
    private string allowGiftReceiptField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string allowGiftWrap {
        get {
            return this.allowGiftWrapField;
        }
        set {
            this.allowGiftWrapField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string allowGiftMessage {
        get {
            return this.allowGiftMessageField;
        }
        set {
            this.allowGiftMessageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string allowGiftReceipt {
        get {
            return this.allowGiftReceiptField;
        }
        set {
            this.allowGiftReceiptField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NewDataSet {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("imageEntities", typeof(imageEntities))]
    [System.Xml.Serialization.XmlElementAttribute("searchresponse", typeof(searchresponse))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
